"""initial schema

Revision ID: c04a71891b92
Revises: 
Create Date: 2026-07-05 18:54:27.324319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c04a71891b92'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('duration_sec', sa.Float(), nullable=True),
    sa.Column('upload_path', sa.String(), nullable=False),
    sa.Column('output_path', sa.String(), nullable=True),
    sa.Column('thumbnail_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('team_a_possession_pct', sa.Float(), nullable=True),
    sa.Column('team_b_possession_pct', sa.Float(), nullable=True),
    sa.Column('player_count', sa.Integer(), nullable=True),
    sa.Column('total_passes', sa.Integer(), nullable=True),
    sa.Column('total_interceptions', sa.Integer(), nullable=True),
    sa.Column('max_player_speed_kmh', sa.Float(), nullable=True),
    sa.Column('max_player_distance_m', sa.Float(), nullable=True),
    sa.Column('has_violations', sa.Boolean(), nullable=False),
    sa.Column('narrative_text', sa.String(), nullable=True),
    sa.Column('report_json_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('team', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_events_video_id'), 'game_events', ['video_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('stage_index', sa.Integer(), nullable=True),
    sa.Column('total_stages', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('tracker_player_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('team', sa.Integer(), nullable=True),
    sa.Column('total_distance_m', sa.Float(), nullable=False),
    sa.Column('avg_speed_kmh', sa.Float(), nullable=False),
    sa.Column('max_speed_kmh', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_video_id'), 'players', ['video_id'], unique=False)
    op.create_table('violations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('start_frame', sa.Integer(), nullable=False),
    sa.Column('end_frame', sa.Integer(), nullable=False),
    sa.Column('violation_type', sa.String(), nullable=False),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_violations_video_id'), 'violations', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_violations_video_id'), table_name='violations')
    op.drop_table('violations')
    op.drop_index(op.f('ix_players_video_id'), table_name='players')
    op.drop_table('players')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_game_events_video_id'), table_name='game_events')
    op.drop_table('game_events')
    op.drop_table('videos')
    # ### end Alembic commands ###
